import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/NavbarDoc";
import Footer from "@/components/shared/Footer";
import GoToTopButton from "@/components/shared/Gototop";
import { QueryProvider } from "../../utils/react-query/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rajis Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <Navbar className="top-5" />
          <div className="w-full min-w-full overflow-hidden">
            {children}
          </div>
          <div className="relative">
            <Footer />
          </div>
        </QueryProvider>
        <GoToTopButton />
      </body>
    </html>
  );
}