import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/NavbarDoc";
import Footer from "@/components/shared/Footer";
import GoToTopButton from "@/components/shared/Gototop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rajis Lab",
  description: "Generated by create next ap p",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative">
          <Navbar className="top-5" />
        </div>
        {children}
        <div className="relative">
          <Footer />
        </div>

        <GoToTopButton />
      </body>
    </html>
  );
}


